# **chapter 4.**  데이터 다루기



## Ch 4.1.



In [ ]:
List_Data = [2, 4, 6, 8, 10, 12]
print(List_Data)

print(List_Data[0], '\n')
print(List_Data[1]+List_Data[2], '\n')
print(List_Data[-1], '\n')
print(List_Data[-6], '\n')

[2, 4, 6, 8, 10, 12]
2 

10 

12 

2 



## Ch 4.2.







In [ ]:
Lst1 = [1, 3, 5, 7]
Lst2 = [2, 4, 6, 8, 10, 12]

print(Lst1, '\n')
print(Lst2, '\n')

print(Lst1.index(7), '\n')
print(Lst1, '\n')

Lst1.append(9)   #Lst1에 9 추가
print(Lst1, '\n')

Lst1.insert(0, 11) #Index 0의 자리에 11 추가
print(Lst1, '\n')

[1, 3, 5, 7] 

[2, 4, 6, 8, 10, 12] 

3 

[1, 3, 5, 7] 

[1, 3, 5, 7, 9] 

[11, 1, 3, 5, 7, 9] 



In [ ]:
Lst1 = [1, 3, 5, 7]
Lst2 = [2, 4, 6, 8, 10, 12]

Lst2.remove(12)    #Lst2 의 12 삭제
print(Lst2, '\n')

Lst1.extend(Lst2)   #Lst1 뒤에 Lst2  추가하기
print(Lst1, '\n')

Lst1.sort()         # 정렬
print(Lst1, '\n')

Lst1.reverse()      # 역으로 정렬
print(Lst1, '\n')

print(Lst1+Lst2)

[2, 4, 6, 8, 10] 

[1, 3, 5, 7, 2, 4, 6, 8, 10] 

[1, 2, 3, 4, 5, 6, 7, 8, 10] 

[10, 8, 7, 6, 5, 4, 3, 2, 1] 

[10, 8, 7, 6, 5, 4, 3, 2, 1, 2, 4, 6, 8, 10]


## Ch 4.3   Numpy 라이브러리 사용



In [ ]:
import numpy as np
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6, 7, 8, 9, 10])
print(arr1)

print(arr1+arr2)    #파이선의 LIST와 다름 : print(Lst1+Lst2)

print(arr1+5)

print(arr1-arr2)

print(arr1-5)

print(arr1*arr2)

print(arr1*2)

print(arr1/arr2)

print(arr1/5)

[1 2 3 4 5]
[ 7  9 11 13 15]
[ 6  7  8  9 10]
[-5 -5 -5 -5 -5]
[-4 -3 -2 -1  0]
[ 6 14 24 36 50]
[ 2  4  6  8 10]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.2 0.4 0.6 0.8 1. ]


## Ch 4.4.   List 비교



In [ ]:
list1=[1, 2, 3, 4, 5]
list2=[6, 7, 8, 9, 10]

# 연산이 되는 경우
print(list1)
print(list1+list2)
print(list1*2)

# 연산이 되지 않는 경우
print(list1*list2)
print(list1/5)
print(list1/list2)
print(list1+5)
print(list1-list2)
print(list1-5)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


TypeError: can't multiply sequence by non-int of type 'list'

## Ch 4.5.   Numpy 의 배열 4칙 연산


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

# 배열 덧셈 c = a + b
c = np.add(a, b)
print(c)

# 배열 뺄셈 c = a - b
c = np.subtract(a, b)
print(c)

# 배열 곱셈 c = a * b
c = np.multiply(a, b)
print(c)

# 배열 나눗셈 c = a / b
c = np.divide(a, b)
print(c)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## Ch 4.6.          Ch4.  PPT 15p 참조



In [ ]:
import numpy as np

list1 = [[1,2], [3,4]]
list2 = [[5,6], [7,8]]

a = np.array(list1)
b = np.array(list2)

c=np.add(a, b)
print(c, "\n")

c = np.dot(a, b)
print(c)

[[ 6  8]
 [10 12]] 

[[19 22]
 [43 50]]


## Ch 4.7.



In [ ]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7])

print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.min())
print(arr.max())
print(arr.cumsum())
print(arr.cumprod())

28
4.0
2.0
4.0
1
7
[ 1  3  6 10 15 21 28]
[   1    2    6   24  120  720 5040]


## Ch 4.8.



In [ ]:
import numpy as np
a = np.zeros(5, dtype=int)
print(a)

a = np.zeros((2,2), dtype=int)
print(a)

a = np.ones(5, dtype=float)
print(a)

a = np.full(5, 9)
print(a)

a=np.empty(5)
print(a)

a=np.eye(3)
print(a)

[0 0 0 0 0]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[9 9 9 9 9]
[1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Ch 4.9.



In [ ]:
a = np.arange(3)
print(a)

a = np.arange(-1, 1, 0.5)
print(a)

a = np.linspace(0, 1, 5)
print(a)

[0 1 2]
[-1.  -0.5  0.   0.5]
[0.   0.25 0.5  0.75 1.  ]


## Ch 4.10.  melt()



In [ ]:
# 프로그램 1
import pandas as pd
df1 = pd.DataFrame(
        [[1, 4],
         [2, 5],
         [3, 6]],
        columns=['a', 'b'])
print(df1, '\n')

df2 = pd.DataFrame(
        {"c" : [7, 8, 9],
         "d" : [10, 11, 12]})
print(df2, '\n')

#프로그램 2
df3 = pd.melt(df1)
print(df3)

df4=pd.melt(df2)
print(df4)

   a  b
0  1  4
1  2  5
2  3  6 

   c   d
0  7  10
1  8  11
2  9  12 

  variable  value
0        a      1
1        a      2
2        a      3
3        b      4
4        b      5
5        b      6
  variable  value
0        c      7
1        c      8
2        c      9
3        d     10
4        d     11
5        d     12


## Ch 4.11. cnacat() :  ppt   21p. 참고



In [ ]:
# 프로그램 3
import pandas as pd
df1 = pd.DataFrame(
        [[1, 4],
         [2, 5],
         [3, 6]],
        columns=['a', 'b'])
print(df1, '\n')

df2 = pd.DataFrame(
        {"c" : [7, 8, 9],
         "d" : [10, 11, 12]})
print(df2, '\n')

df4 = pd.concat([df1, df1], axis=0)
print("df4: (axis=0)\n",df4, '\n')

df4 = pd.concat([df1, df1], axis=1)
print("df4: (axis=1)\n",df4, '\n')

df5= pd.concat([df1, df2], axis=0)
print(df5, '\n')

df6 = pd.concat([df1, df2], axis=1)
print(df6, '\n')

   a  b
0  1  4
1  2  5
2  3  6 

   c   d
0  7  10
1  8  11
2  9  12 

df4: (axis=0)
    a  b
0  1  4
1  2  5
2  3  6
0  1  4
1  2  5
2  3  6 

df4: (axis=1)
    a  b  a  b
0  1  4  1  4
1  2  5  2  5
2  3  6  3  6 

     a    b    c     d
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
0  NaN  NaN  7.0  10.0
1  NaN  NaN  8.0  11.0
2  NaN  NaN  9.0  12.0 

   a  b  c   d
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12 



## Ch 4.12. merge()



In [ ]:
import pandas as pd
df_x = pd.DataFrame(
        [['A', 1],
         ['B', 2],
         ['C', 3]],
        columns=['x1', 'x2'])
print(df_x, '\n')

df_y = pd.DataFrame(
        {"x1" : ['B', 'C', 'D'],
         "x3" : [2, 3, 4]})
print(df_y, '\n')

print(pd.merge(df_x, df_y, how='left'), '\n')

print(pd.merge(df_x, df_y, how='right'), '\n')

print(pd.merge(df_y, df_x))

  x1  x2
0  A   1
1  B   2
2  C   3 

  x1  x3
0  B   2
1  C   3
2  D   4 

  x1  x2   x3
0  A   1  NaN
1  B   2  2.0
2  C   3  3.0 

  x1   x2  x3
0  B  2.0   2
1  C  3.0   3
2  D  NaN   4 

  x1  x3  x2
0  B   2   2
1  C   3   3


## Ch 4.13. pivot()



In [ ]:
import pandas as pd
df = pd.DataFrame(
   [['20225001','A', 77],
   ['20225001','B', 80],
   ['20225002','A', 85],
   ['20225002','B', 82],
   ['20225003','A', 95],
   ['20225003','B', 90]],
    columns=['ID_num','Subject', 'Score'])
print(df, '\n')

df_pivot = df.pivot(index = 'ID_num',
        columns='Subject', values = 'Score')
print(df_pivot, '\n')

df_pivot = df.pivot(index='ID_num', columns='Subject').sum(axis=1)
print(df_pivot, '\n')

     ID_num Subject  Score
0  20225001       A     77
1  20225001       B     80
2  20225002       A     85
3  20225002       B     82
4  20225003       A     95
5  20225003       B     90 

Subject    A   B
ID_num          
20225001  77  80
20225002  85  82
20225003  95  90 

ID_num
20225001    157
20225002    167
20225003    185
dtype: int64 



## Ch 4.14. groupby()



In [ ]:
import pandas as pd
# <예제 2-13>의 df 사용
df = pd.DataFrame(
   [['20225001','A', 77],
   ['20225001','B', 80],
   ['20225002','A', 85],
   ['20225002','B', 82],
   ['20225003','A', 95],
   ['20225003','B', 90]],
    columns=['ID_num','Subject', 'Score'])

print(df, '\n')
group_mean = df.groupby(by='Subject')['Score'].mean()
print(group_mean)

     ID_num Subject  Score
0  20225001       A     77
1  20225001       B     80
2  20225002       A     85
3  20225002       B     82
4  20225003       A     95
5  20225003       B     90 

Subject
A    85.666667
B    84.000000
Name: Score, dtype: float64


## Ch 4.15. sort_values()



In [ ]:
import pandas as pd
# <예제 2-13>의 df 사용
df = pd.DataFrame([
   ['20225001','A', 77],
   ['20225001','B', 80],
   ['20225002','A', 85],
   ['20225002','B', 82],
   ['20225003','A', 95],
   ['20225003','B', 90]],
    columns=['ID_num','Subject', 'Score'])
print(df, '\n')

print(df.sort_values(by='Score', ascending=False))

print(df.sort_values(by=['Score', 'Subject']))

print(df.sort_values(by=['Subject', 'Score']))

     ID_num Subject  Score
0  20225001       A     77
1  20225001       B     80
2  20225002       A     85
3  20225002       B     82
4  20225003       A     95
5  20225003       B     90 

     ID_num Subject  Score
4  20225003       A     95
5  20225003       B     90
2  20225002       A     85
3  20225002       B     82
1  20225001       B     80
0  20225001       A     77
     ID_num Subject  Score
0  20225001       A     77
1  20225001       B     80
3  20225002       B     82
2  20225002       A     85
5  20225003       B     90
4  20225003       A     95
     ID_num Subject  Score
0  20225001       A     77
2  20225002       A     85
4  20225003       A     95
1  20225001       B     80
3  20225002       B     82
5  20225003       B     90
